### ISSUE TITLE
Minestrapp Slate seems to Override the generation of all Quark's Limestone

### ISSUE THREAD

**Issue by mysteryblock** [Delocuro/Minestrapp-1.12#4] opened 2017-10-19 09:56 UTC
As the title says, the Slate in Minestrapp seems to disallow any limestone from the Quark mod to generate, which is most noticeable in ravines. I've also informed Quark's author of this. Hopefully we can get them to play along!

**Comment by werty1124** [comment] 2017-10-21 04:22
I'll take a look at fixing this ASAP!

**Comment by Delocuro** [comment] 2017-10-22 03:26
Looks like it's because Quark & Minestrapp go about implementing their stones the same way. Minestrapp generates Slate by choosing one of the three Vanilla decor stone types (Granite, Diorite, or Andesite) and replacing it with Slate depending on what biome it's in.

Slate doesn't generate at all in Cold or Snowy biomes, so you should still be able to find Limestone in Frozen River, Frozen Ocean, Stone Beach, and Cold Beach biomes.

If you're able, try finding one of those biomes and let me know if Limestone seems to be generating at all - if it still isn't generating in those biomes then the problem isn't Slate, but Minestrapp's whole biome-specific stone gen, which means it may be a bit more complicated to fix...

**Comment by mysteryblock** [comment] 2017-10-22 18:17
I'll go find some cold biomes and get back to you! Thank you for the prompt reply.

**Comment by mysteryblock** [comment] 2017-10-25 06:53
I haven't been able to find any limestone in cold nor warm biomes yet. That doesn't mean it's not there, howerver, as limestone seemed to generate nearly exclusively in ravines and I'm finding few of those in cold biomes.

**Comment by mysteryblock** [comment] 2017-10-25 06:54
Also, I am including biomes o' plenty cold biomes as well as vanilla biomes when I say I haven't been able to find any in cold biomes so far.

**Comment by Delocuro** [comment] 2017-10-28 00:51
Ah, yeah, then it's for sure a problem of Minestrapp generating first. That could be a little more complicated to fix - I'm not really sure how to change Minestrapp's level of worldgen priority - but I'll look into it and see if I can figure out how to fix it.

**Comment by mysteryblock** [comment] 2017-10-28 00:55
I'm a novice to coding, at best. However, instead of changing how it generates, it could perhaps generate a certain percentage less if it detects quark. Not sure that'd really solve anything, but I figured I'd throw it out  there.

**Comment by mysteryblock** [comment] 2017-11-17 23:54
Finally found some Quark slate in the Taiga biome in a new world. It's still pretty uncommon in the world at large, but I am glad to at least have a way to obtain it now.

**Comment by Delocuro** [comment] 2017-12-30 00:53
Okay, I think part of the problem may be fixed - apparently Slate was overriding all Granite, Andesite, and Diorite in Ocean and Mushroom Island biomes. Should be fixed now, so try generating a new world when 5.2.0 comes out and let me know if it seems to be appearing any more frequently.

**Comment by ghost** [comment] 2018-02-06 04:33
While I'm not the OP, I will chime in and say I've been able to find Quark Limestone, and Minestrapp Slate in worlds I've generated with both mods.

**Comment by Delocuro** [comment] 2018-02-06 05:14
Cool - closing this for now since I haven't heard otherwise, but let me know if anyone runs into the issue again.

**Closed as completed by Delocuro** 2018-02-06 05:14 UTC
