### ISSUE TITLE
Crusher crash with ticking block entity

### ISSUE THREAD

**Issue by Zarvera** [Delocuro/Minestrapp-1.12#30] opened 2018-11-06 13:11 UTC
Upon shoving Glowstone into the Crusher as soon as the first got processed server crashed with this:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.7.4.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
  AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-108-universal.jar)
  LoadingPlugin (Quark-r1.5-130.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 11/6/18 4:05 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at minestrapp.block.tileentity.TileEntityCrusher.canSmelt(TileEntityCrusher.java:278)
	at minestrapp.block.tileentity.TileEntityCrusher.func_73660_a(TileEntityCrusher.java:221)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at minestrapp.block.tileentity.TileEntityCrusher.canSmelt(TileEntityCrusher.java:278)
	at minestrapp.block.tileentity.TileEntityCrusher.func_73660_a(TileEntityCrusher.java:221)

-- Block entity being ticked --
Details:
	Name: minestrapp:tileentitycrusher // minestrapp.block.tileentity.TileEntityCrusher
	Block type: ID #733 (tile.crusher // minestrapp.block.BlockCrusher // minestrapp:crusher)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (2015,77,871), Chunk: (at 15,4,7 in 125,54; contains blocks 2000,0,864 to 2015,255,879), Region: (3,1; contains chunks 96,32 to 127,63, blocks 1536,0,512 to 2047,255,1023)
	Actual block type: ID #733 (tile.crusher // minestrapp.block.BlockCrusher // minestrapp:crusher)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Zarvera'/270, l='New World', x=2015.36, y=77.00, z=874.65]]
	Chunk stats: ServerChunkCache: 914 Drop: 0
	Level seed: -936123753329573071
	Level generator: ID 10 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (1232,64,1248), Chunk: (at 0,4,0 in 77,78; contains blocks 1232,0,1248 to 1247,255,1263), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
	Level time: 4729120 game time, 2524178 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 55696 (now: false), thunder time: 100830 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2261237744 bytes (2156 MB) / 3490185216 bytes (3328 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6144m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version           | Source                                          | Signature                                |
	|:--------- |:-------------------- |:----------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                  | 9.42              | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.5.2772-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.5.2772      | forge-1.12.2-14.23.5.2772-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | advancedrocketrycore | 1                 | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | foamfixcore          | 7.7.4             | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | libvulpes            | 0.2.8.-39         | LibVulpes-1.12.2-0.2.8-39-universal.jar         | None                                     |
	| UCHIJAAAA | advancedrocketry     | 1.4.1.-108        | AdvancedRocketry-1.12.2-1.4.1-108-universal.jar | None                                     |
	| UCHIJAAAA | aether_legacy        | 1.12.2-v3.2       | aether_legacy-1.12.2-v3.2.jar                   | None                                     |
	| UCHIJAAAA | mcjtylib_ng          | 3.0.6             | mcjtylib-1.12-3.0.6.jar                         | None                                     |
	| UCHIJAAAA | hologui              | 0.0.3-beta        | hologui-1.12-0.0.3-beta.jar                     | None                                     |
	| UCHIJAAAA | ariente              | 0.0.4-alpha       | ariente-1.12-0.0.4-alpha.jar                    | None                                     |
	| UCHIJAAAA | baubles              | 1.5.2             | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCHIJAAAA | fp                   | 26.3.417          | Futurepack-1.12.2-26.3.417.jar                  | 3ad693059337b95c41b649ec9f29c4a6e8282586 |
	| UCHIJAAAA | crafttweaker         | 4.1.11            | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| UCHIJAAAA | astralsorcery        | 1.9.4             | astralsorcery-1.12.2-1.9.4.jar                  | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| UCHIJAAAA | quark                | r1.5-130          | Quark-r1.5-130.jar                              | None                                     |
	| UCHIJAAAA | autoreglib           | 1.3-20            | AutoRegLib-1.3-20.jar                           | None                                     |
	| UCHIJAAAA | betterbuilderswands  | 0.12.0            | BetterBuildersWands-1.12-0.12.0.251+d6c4d93.jar | None                                     |
	| UCHIJAAAA | bookshelf            | 2.3.567           | Bookshelf-1.12.2-2.3.567.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | brytemod             | 1.0.0             | brytemod-1.0.jar                                | None                                     |
	| UCHIJAAAA | mcmultipart          | 2.5.3             | MCMultiPart-2.5.3.jar                           | None                                     |
	| UCHIJAAAA | redstoneflux         | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | sonarcore            | 5.0.16            | sonarcore-1.12.2-5.0.16-16.jar                  | None                                     |
	| UCHIJAAAA | calculator           | 5.0.9             | calculator-1.12.2-5.0.9-9.jar                   | None                                     |
	| UCHIJAAAA | clockworkphase2      | 1.12-0.1.5        | clockworkphase2-1.12-0.1.5.jar                  | None                                     |
	| UCHIJAAAA | ctgui                | 1.0.0             | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| UCHIJAAAA | mtlib                | 3.0.5             | MTLib-3.0.5.jar                                 | None                                     |
	| UCHIJAAAA | modtweaker           | 4.0.15            | modtweaker-4.0.15.jar                           | None                                     |
	| UCHIJAAAA | jei                  | 4.12.1.217        | jei_1.12.2-4.12.1.217.jar                       | None                                     |
	| UCHIJAAAA | crafttweakerjei      | 2.0.2             | CraftTweaker2-1.12-4.1.11.jar                   | None                                     |
	| UCHIJAAAA | ctm                  | MC1.12.2-0.3.2.20 | CTM-MC1.12.2-0.3.2.20.jar                       | None                                     |
	| UCHIJAAAA | cyclopscore          | 0.11.10           | CyclopsCore-1.12.2-0.11.10.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | dbag                 | 1.12.2-4.0        | dbag-4.0.jar                                    | None                                     |
	| UCHIJAAAA | diethopper           | 1.1               | diethopper-1.1.jar                              | None                                     |
	| UCHIJAAAA | drawbridges          | 0.1               | Drawbridges-1.0.1.jar                           | None                                     |
	| UCHIJAAAA | dungeonmobs          | 5.5.1             | dungeonmobs-5.5.1-MC1.12.2.jar                  | None                                     |
	| UCHIJAAAA | ebwizardry           | 4.1.2             | Electroblob's+Wizardry+-+4.1.2+-+MC+1.12.2.jar  | None                                     |
	| UCHIJAAAA | eplus                | 5.0.173           | EnchantingPlus-1.12.2-5.0.173.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | enchdesc             | 1.1.12            | EnchantmentDescriptions-1.12.2-1.1.12.jar       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | endercompass         | 1.2.6.2           | EnderCompass-1.12-1.2.6.2.jar                   | None                                     |
	| UCHIJAAAA | evilcraft            | 0.10.63           | EvilCraft-1.12.2-0.10.63.jar                    | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCHIJAAAA | evilcraftcompat      | 1.0.0             | EvilCraft-1.12.2-0.10.63.jar                    | None                                     |
	| UCHIJAAAA | externaltweaker      | 0.3               | externaltweaker-1.12-0.3.jar                    | None                                     |
	| UCHIJAAAA | fastleafdecay        | v14               | FastLeafDecay-v14.jar                           | None                                     |
	| UCHIJAAAA | finite-water-control | 1.0               | finite-water-control-1.12-1.0.jar               | None                                     |
	| UCHIJAAAA | foamfix              | 0.10.2-1.12.2     | foamfix-0.10.2-1.12.2.jar                       | None                                     |
	| UCHIJAAAA | forgelin             | 1.7.4             | Forgelin-1.7.4.jar                              | None                                     |
	| UCHIJAAAA | fp.api               | 1.1.0             | Futurepack-1.12.2-26.3.417.jar                  | None                                     |
	| UCHIJAAAA | waila                | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| UCHIJAAAA | mantle               | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                        | None                                     |
	| UCHIJAAAA | inspirations         | 1.12.2-0.2.3      | Inspirations-1.12.2-0.2.3.jar                   | None                                     |
	| UCHIJAAAA | iymts_mob_mod        | 0.2.0             | iymts_mob_mod_1.12.2-2611-ver.0.2.0.jar         | None                                     |
	| UCHIJAAAA | journeymap           | 1.12.2-5.5.2      | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | jeresources          | 0.8.9.48          | JustEnoughResources-1.12.2-0.8.9.48.jar         | None                                     |
	| UCHIJAAAA | magneticraft         | 2.5.2             | Magneticraft_1.12-2.5.2-dev.jar                 | None                                     |
	| UCHIJAAAA | manawell             | 0.0.2             | manawell-1.12--0.0.2.jar                        | None                                     |
	| UCHIJAAAA | matteroverdrive      | 0.6.2.0           | MatterOverdrive-1.12.2-0.6.2.0-universal.jar    | None                                     |
	| UCHIJAAAA | metalworks           | 1.5.0             | Metalworks-1.5.0.jar                            | None                                     |
	| UCHIJAAAA | minestrapp           | 5.4.0A            | Minestrappolation+5.5.0.jar                     | None                                     |
	| UCHIJAAAA | modelloader          | 1.1.5             | modelloader-1.1.5.jar                           | None                                     |
	| UCHIJAAAA | naturescompass       | 1.5.1             | NaturesCompass-1.12.2-1.5.1.jar                 | None                                     |
	| UCHIJAAAA | nomobbat             | 1.1               | NoBat-1.12.2-frg14.23.3.2655.jar                | None                                     |
	| UCHIJAAAA | nmsot                | 1.2.2-mc1.12.2    | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar         | None                                     |
	| UCHIJAAAA | recipehandler        | 0.12              | NoMoreRecipeConflict-0.12(1.12.2).jar           | None                                     |
	| UCHIJAAAA | norecipebook         | 1.2.1             | noRecipeBook_v1.2.2formc1.12.2.jar              | None                                     |
	| UCHIJAAAA | placebo              | 1.5.0             | Placebo-1.12.2-1.5.0.jar                        | None                                     |
	| UCHIJAAAA | practicallogistics2  | 3.0.4             | practicallogistics2-1.12.2-3.0.4.jar            | None                                     |
	| UCHIJAAAA | rv                   | 0.0.31            | RavenousVoid-0.0.31.jar                         | None                                     |
	| UCHIJAAAA | refinedstorage       | 1.6.9             | refinedstorage-1.6.9.jar                        | None                                     |
	| UCHIJAAAA | rustic               | 1.0.12            | rustic-1.0.12.jar                               | None                                     |
	| UCHIJAAAA | cardboardboxes       | 0.0.2.7           | SBM-CardboardBoxes-1.12.2-0.0.2b7.jar           | None                                     |
	| UCHIJAAAA | t3s4ebw              | 1.0               | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar    | None                                     |
	| UCHIJAAAA | shadowmc             | 3.8.0             | ShadowMC-1.12-3.8.0.jar                         | None                                     |
	| UCHIJAAAA | solar                | 1.0.3             | Solar-1.0.3.jar                                 | None                                     |
	| UCHIJAAAA | stg                  | 1.12.2-1.2.3      | stg-1.12.2-1.2.3.jar                            | None                                     |
	| UCHIJAAAA | tammodized           | 0.15.5            | TamModized-1.12.1-0.15.5.jar                    | None                                     |
	| UCHIJAAAA | tesla                | 1.0.63            | Tesla-1.12.2-1.0.63.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | toroquest            | 1.12.2-5.2        | toroquest-1.12.2-5.2.jar                        | None                                     |
	| UCHIJAAAA | trumpetskeleton      | 1.12-1.0.2.1      | trumpetskeleton-1.12-1.0.2.1.jar                | None                                     |
	| UCHIJAAAA | underwaterutilities  | @VERSION@         | UnderwaterUtilities-1.12-1.3.3.jar              | None                                     |
	| UCHIJAAAA | of                   | 0.11              | Useful+Interior+-+0.11+[1.12.2].jar             | None                                     |
	| UCHIJAAAA | voidcraft            | 0.26.10           | VoidCraft-1.12-0.26.10.jar                      | None                                     |
	| UCHIJAAAA | wailaharvestability  | 1.1.12            | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| UCHIJAAAA | waterworks           | 1.12.2-1.0.12     | Waterworks-1.12.2-1.0.12.jar                    | None                                     |
	| UCHIJAAAA | witherskelefix       | 2.6.1             | Wither+Skeleton+Tweaks-1.12.2-2.6.1.jar         | None                                     |
	| UCHIJAAAA | worleycaves          | 1.3.0             | worleycaves-1.3.0.jar                           | None                                     |
	| UCHIJAAAA | wts                  | 1.1.0             | WTS-1.1.0.jar                                   | None                                     |
	| UCHIJAAAA | kiwi                 | 0.2.4.2           | Kiwi-1.12.2-0.2.4.2.jar                         | None                                     |
	| UCHIJAAAA | cuisine              | 0.3.1-build568    | Cuisine-0.3.1-build568.jar                      | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.7.4.jar)
  
Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
  com.chocohead.biab.BornInABarn
AstralCore (astralsorcery-1.12.2-1.9.4.jar)
  
AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.1-108-universal.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
LoadingPlugin (Quark-r1.5-130.jar)
  vazkii.quark.base.asm.ClassTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- WailaPlugin (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Zarvera'/270, l='New World', x=2015.36, y=77.00, z=874.65]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by ZigTheHedge** [comment] 2019-03-11 12:17
Having the same issue.

**Comment by Delocuro** [comment] 2019-03-11 13:25
@ZigTheHedge Interesting... you using any of the same mods listed in Zarvera's crash log? I've had no luck recreating the issue in Vanilla Minestrapp, so it appears to be some mod compat issue, but it'll be hard to fix until I have a better idea of which one's causing it.

**Comment by ZigTheHedge** [comment] 2019-03-11 17:13
Just reproduced the crash with only minestrap and JEI installed.
https://pastebin.com/62RkyFbX

Steps to reproduce:
1. Place crusher
2. Insert coal block
3. Insert stack of vanilla cauldrons
4. Wait a couple of seconds
5. Profit! 

Maybe it also happens with another blocks, I didn't check.

**Comment by Delocuro** [comment] 2019-03-11 19:40
O_o huh... so yours is happening with Cauldrons instead of Glowstone? Hmmm... doesn't look like there's any issues with Forge being out of date or anything, so it's extremely strange that I haven't been able to replicate it thus far. I'll do some more testing this evening and see if I can figure anything out...

**Comment by Zarvera** [comment] 2019-03-12 17:14
> @ZigTheHedge Interesting... you using any of the same mods listed in Zarvera's crash log? I've had no luck recreating the issue in Vanilla Minestrapp, so it appears to be some mod compat issue, but it'll be hard to fix until I have a better idea of which one's causing it.

A-akchully if you remember we moved to discuss it on the CF and i did dismantled my instance and in the end just made a pure forge+Minestrapp instance and it was still crashing, so it's not mod compatibility issue.
Also it's not just Glowstone. It's basically anything that can be put inside. It did worked sometimes, though. 
It's such a rare and weird issue it seems. The only thing i could add is that i build my instances in MultiMC, if that could potentially be of any help at all

**Comment by Delocuro** [comment] 2019-03-12 17:28
Hmmmmmm, maybe it's somehow MultiMC related, then? Were you using MultiMC on yours, @ZigTheHedge ? I've seriously had no luck recreating this on either of my computers, nor in the dev workspace, so I'm really at a loss here.

**Comment by ZigTheHedge** [comment] 2019-03-13 18:27
Nope. I'm using vanilla launcher.

**Comment by ZigTheHedge** [comment] 2019-03-13 18:46
Here you go:
**CrusherRecipes.java**
`		this.addCrusherRecipe(new ItemStack(Items.CAULDRON), new ItemStack(Items.IRON_NUGGET, 32), null, 0, 0.05F);`
**TileEntityCrusher.java**
`			ItemStack bonusDrop = CrusherRecipes.instance().getExtra((ItemStack)this.inventory.get(0));
				int resBonus = bonus.getCount() + bonusDrop.getCount();
`
bonusDrop is **null** for most of recipes.

**Comment by Delocuro** [comment] 2019-03-13 19:41
Yeah, that's deliberate -- if I remember right, there's a null check when it gets the recipe results, and if it has null as a bonus drop it just doesn't affect the bonus slot at all. Regardless, even if the null bonus drop somehow was causing issues, I'm mostly confused as to why I can't seem to recreate the issue -- if the recipe registry is messed up, it seems like it would affect all clients...

**Comment by ZigTheHedge** [comment] 2019-03-14 05:23
It may be deliberate, but you miss a null check in TileEntityCrusher::canSmelt ;) Bug reproduced in dev environment using your current master-branch in github. Maybe it is not the most recent commit? And that is the reason why you cannot reproduce the bug in your local environment?

**Comment by Delocuro** [comment] 2019-03-15 15:01
No, the latest commit on the dev branch should be the latest version of the Crusher code -- I haven't edited anything in those classes in a long while. Regardless, I've periodically tried figuring this one out since back in November when the issue was first posted, so something else is going on that's causing the issue to not happen on all clients. I can also confirm it's not happening on the Minestrapp official server, either -- someone else recently reported the crash occurring with Wheat, but myself and others have been actively crushing Wheat on the server for several updates without any hint of a crash. Also doesn't seem to be happening on most modpacks -- I've been keeping an eye on the Astroblock and Ascension of the Realms servers, but thus far I've heard no reports of any Minestrapp-related crashes from either.

Anyway, I can change the nulls to ItemStack.EMPTY and see if that fixes it, but it's gonna be hard to test since I don't have any way of knowing whether or not it's broken. I'll let you know when I've pushed the change to Github -- if you're able to test it and see if it's still broken on your end, that'd help a ton. Thanks!

**Comment by ZigTheHedge** [comment] 2019-03-15 19:57
There is an easier way...
`				int resBonus = 0;
				if(bonusDrop != null)
					resBonus = bonus.getCount() + bonusDrop.getCount();
				else
					resBonus = bonus.getCount();`
And sure, I'll check your fix when it will become available.

**Comment by ZigTheHedge** [comment] 2019-03-15 19:59
There is an easier way...
`int resBonus = 0; 
if(bonusDrop != null) resBonus = bonus.getCount() + bonusDrop.getCount(); 
else resBonus = bonus.getCount();`
And sure, I'll check your fix when it will become available.

**Comment by Delocuro** [comment] 2019-03-16 22:16
@ZigTheHedge Oh, good catch -- that was *way* easier that whatever dumb hack I was about to try, lmao. Just pushed the change, so *hopefully* it might be fixed now.

**Comment by ZigTheHedge** [comment] 2019-03-17 07:32
Yep. Fixed. Thanks! :)

**Comment by Delocuro** [comment] 2019-03-17 18:14
Awesome! Glad we can finally check one of these off the list, lol

**Closed as completed by Delocuro** 2019-03-17 18:14 UTC
Labels: CRASH, Untested
